FROM golang:1.12-alpine
RUN apk add --no-cache ca-certificates git
WORKDIR /go/vault-manager
COPY . .
# run unit tests
RUN CGO_ENABLED=0 GOOS=linux go test ./...
# run build
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo ./cmd/vault-manager
