FROM registry.access.redhat.com/ubi8/go-toolset:latest as builder
COPY . .
RUN make gobuild

FROM quay.io/app-sre/centos:7
ENV PACKAGES="jq git docker unzip wget"
ENV BATS_VERSION="v0.4.0"

RUN yum install -y epel-release && \
    yum install -y $PACKAGES && \
    rpm -q --queryformat "" $PACKAGES

RUN git clone https://github.com/sstephenson/bats.git && \
    git --git-dir=bats/.git checkout -b $BATS_VERSION $BATS_VERSION >/dev/null && \
    bats/install.sh /usr/local

RUN wget https://releases.hashicorp.com/vault/1.3.0/vault_1.3.0_linux_amd64.zip && unzip vault_1.3.0_linux_amd64.zip && mv vault /usr/bin

COPY tests/ /tests/
COPY --from=builder /opt/app-root/src/vault-manager /bin/

WORKDIR /tests

CMD ["bash", "run-tests.sh"]
