apiVersion: v1
kind: Template
metadata:
  name: vault-manager
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: vault-manager
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: vault-manager
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "vault-manager design does not adequately account for multiple replicas"
      ignore-check.kube-linter.io/no-readiness-probe: "vault-manager is not getting traffic"
    name: vault-manager
  spec:
    replicas: ${{REPLICAS}}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: vault-manager
    template:
      metadata:
        labels:
          app: vault-manager
          component: qontract-reconcile
      spec:
        serviceAccountName: vault-manager
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: vault-manager
          command: ["/bin/sh"]
          args: 
          - "-c"
          - "/vault-manager -dry-run=${DRY_RUN} -run-once=${RUN_ONCE} -thread-pool-size=${THREAD_POOL_SIZE}"
          env:
          - name: GRAPHQL_QUERY_FILE
            value: ${GRAPHQL_QUERY_FILE}
          - name: DISABLE_IDENTITY
            value: ${DISABLE_IDENTITY}
          - name: RECONCILE_SLEEP_TIME
            value: ${RECONCILE_SLEEP_TIME}
          - name: METRICS_SERVER_PORT
            value: ${METRICS_SERVER_PORT}
          - name: GRAPHQL_SERVER
            valueFrom:
              secretKeyRef:
                key: endpoint_url
                name: ${GQL_SECRET_NAME}
          - name: GRAPHQL_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: ${GQL_SECRET_NAME}
          - name: GRAPHQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: ${GQL_SECRET_NAME}
          - name: VAULT_ADDR
            value: ${VAULT_ADDR}
          - name: VAULT_AUTHTYPE
            valueFrom:
              secretKeyRef:
                key: auth_type
                name: ${VAULT_SECRET_NAME}
          - name: VAULT_ROLE_ID
            valueFrom:
              secretKeyRef:
                key: role_id
                name: ${VAULT_SECRET_NAME}
          - name: VAULT_SECRET_ID
            valueFrom:
              secretKeyRef:
                key: secret_id
                name: ${VAULT_SECRET_NAME}
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
parameters:
- name: IMAGE
  value: quay.io/app-sre/vault-manager
  displayName: vault-manager image
  description: vault-manager docker image. Defaults to quay.io/app-sre/vault-manager
- name: IMAGE_TAG
  value: latest
  displayName: vault-manager version
  description: vault-manager version which defaults to latest
- name: MEMORY_REQUESTS
  value: 150Mi
- name: MEMORY_LIMIT
  value: 250Mi
- name: CPU_REQUESTS
  value: 100m
- name: CPU_LIMIT
  value: 200m
- name: REPLICAS
  value: '3'
- name: RECONCILE_SLEEP_TIME
  value: '15m'
- name: DRY_RUN
  description: runs vault-manager in dry-run mode when true
  value: 'false'
- name: RUN_ONCE
  description: exits after one reconciliation attempt when true
  value: 'true'
- name: METRICS_SERVER_PORT
  description: port to begin http server on that exposes /metrics
  value: '9090'
- name: VAULT_SECRET_NAME
  value: vault-creds
- name: GQL_SECRET_NAME
  value: gql-creds
- name: THREAD_POOL_SIZE
  value: '10'
- name: GRAPHQL_QUERY_FILE
  value: '/query.graphql'
- name: VAULT_ADDR
  description: vault endpoint URL
  value: ''
- name: DISABLE_IDENTITY
  description: disables entity and group toplevels when set
  value: ''
